name: Semver

on: [pull_request_target]

jobs:
  check-semver:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check semver
        uses: u9g/cargo-semver-checks-action@no-anno
        with:
          pr: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
