name: Semver

on: [pull_request]

jobs:
  check-semver:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check semver
        uses: u9g/cargo-semver-checks-action@4fcb983d4609d0f8224b1101d4b87e90aa686385
        with:
          pr: true
