name: Semver

on: [pull_request]

jobs:
  check-semver:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Check semver
        uses: u9g/cargo-semver-checks-action@HEAD
        with:
          pr: true
